-   id: keats-version-up
    name: keats-version-up
    description: creates `requirements.txt` file from `pyproject.toml`
    entry: keats_version_up_hook
    language: python
    always_run: false
    pass_filenames: true