-   id: keats-version-up
    name: keats-version-up
    description: creates `requirements.txt` file from `pyproject.toml`
    entry: keats version up
    language: python
    always_run: true
    pass_filenames: true