-   id: keats-version-up
    name: keats-version-up
    description: bumps package information from `pyproject.toml` to `<pkg>/__version__.py`
    entry: keats_version_up_hook
    always_run: false
    pass_filenames: true