import os
import toml
from os.path import join, abspath, dirname, isfile, isdir
import fire
from warnings import warn
from .version import __version__, __name__
from .update_change_log import update_changelog_interactive
from termcolor import cprint
from .changelog import ChangeLog


PYPROJECT = "pyproject.toml"
RED = "\u001b[31m"
RESET = "\u001b[0m"
VERSIONPY = "version.py"


def err(msg):
    return RED + msg + RESET


here = abspath(dirname(__file__))


class Keats(object):
    """Manage package version, releases, and changelogs."""

    def __init__(self, directory=os.getcwd(), filename=PYPROJECT):
        self._path = join(directory, filename)
        self._directory = directory
        if not isfile(self._path):
            warn(
                err(
                    "Cannot run keats. No {} file found in currenct directory.".format(
                        PYPROJECT
                    )
                )
            )

    def _keats(self):
        return self.__class__(here)

    @property
    def config(self):
        """
        Return the toml file information.

        :return:
        :rtype:
        """
        return toml.load(self._path)

    def _local_pkg_path(self):
        return self._local_path(self.package())

    def _local_test_path(self):
        return self._local_path("tests")

    def _local_path(self, path):
        return abspath(join(self._directory, path))

    def _get(self, key):
        return self.config["tool"]["poetry"].get(key, None)

    def format(self):
        """
        Run the format script.

        :return:
        :rtype:
        """
        paths = [self._local_path(p) for p in self.packages() + ["tests"]]
        self._cmd(" ".join(["black"] + paths))

    def packages(self):
        """
        Return all listed packaged in the pyproject.toml file. Note that this
        does not consider * files.

        :return: list of package names
        :rtype: list
        """
        if "packages" in self.config["tool"]["poetry"]:
            pkgs = []
            for pkg in self.config["tool"]["poetry"]["packages"]:
                if "from" in pkg:
                    pkgs.append(join(pkg["from"], pkg["include"]))
                else:
                    pkgs.append(pkg["include"])
        else:
            pkgs = [self._get("name")]
        return pkgs

    def package(self):
        """
        Return the estimated main package from the pyproject.toml file.

        :return: version
        :rtype: basestring
        """
        return self.packages()[0]

    def v(self):
        """
        Return the keats version number.
        :return:
        :rtype:
        """
        return __name__ + " " + __version__

    def version(self):
        """
        Return the version from the pyproject.toml file

        :return: version
        :rtype: basestring
        """
        return self._get("version")

    def authors(self):
        """
        Return the list of authors from the pyproject.toml file.

        :return: author list
        :rtype: list
        """
        return self._get("athors")

    def up(self, version=None):
        """
        Update the package version from the pyproject.toml file.

        :param version: if provided, bump the version number (optional)
        :type version: basestring
        :return: the version
        :rtype: basestring
        """
        if version is None:
            self._write()
        else:
            self.bump(version)
        return self.version()

    def bump(self, version=None):
        if version is None:
            self._cmd("poetry version")
        else:
            self._cmd("poetry version {}".format(version))
        self._write()
        return self.changelog().new

    def _version_py(self):
        return join(self._local_pkg_path(), VERSIONPY)

    def info(self):
        """
        Return package information from the toml file.

        :return:
        :rtype:
        """
        toml_info = dict(self.config["tool"]["poetry"])
        pkg_info = {
            "version": toml_info["version"],
            "name": toml_info["name"],
            "title": toml_info["name"],
            "authors": toml_info.get("authors", list()),
            "repo": toml_info.get("repo", None),
            "homepage": toml_info.get("homepage", None),
            "description": toml_info.get("description", None),
        }
        return pkg_info

    def _write(self, with_confirm=False):
        pkg_info = self.info()
        path = self._version_py()
        if with_confirm:
            ans = input("Write to '{}'?".format(path))
        else:
            ans = ""
        if ans.strip() == "" or ans.strip().lower() == "y":
            with open(path, "w") as f:
                lines = [
                    "# {}\n".format(VERSIONPY),
                    "# autogenerated by Keats=={}\n".format(__version__),
                ]
                for k, v in pkg_info.items():
                    if isinstance(v, str):
                        v = '"{}"'.format(v)
                    lines.append("__{}__ = {}\n".format(k, v))
                f.writelines(lines)
        else:
            print("no files written")

    def changelog(self):
        return ChangeLog(self)


def main():
    fire.Fire(Keats)
